### ISSUE TITLE
Trio 1 - Game Module

### ISSUE THREAD

**Issue by lucasgcaldas** [UnBParadigmas2023-2/2023.2_G1_Funcional_Jogo_da_Velha#2]
Desenvolvimento do game - Parte Inicial

**Comment by nando3d3** [comment]
Criei o main.hs que define a cor de fundo da janela, o estado inicial do jogo, funções para renderização e atualização do jogo. A janela do jogo é configurada com dimensões e título.

**Comment by lucasgcaldas** [comment]
Criei a Game.hs, que separa a estruta de encapsulamento do jogo.
