### ISSUE TITLE
Trio 3 - Implementação

### ISSUE THREAD

**Issue by nando3d3** [UnBParadigmas2023-2/2023.2_G1_Funcional_Jogo_da_Velha#4]
Implementação do jogo da velha, incluindo a lógica de jogo, a interação do jogador e a funcionalidade geral do jogo.

**Comment by deboracaires** [comment]
A implementação da parte lógica foi realizada porém com alguns warnings que creio que Rodolfo resolveu em sua branch. Porém elas ainda não se encontram na main
